microvm-nix/microvm.nix

flake.nix, pkgs/kvmtool.nix
- fix linking against bfd
- pin git revison to avoid breaking hash
- more secure https over git protocol for fetching
- allow to override dependencies by using callPackage
=> kvmtool: 2021-07-16 -> 2021-08-31

nixos-modules/microvm/hypervisor/firecracker.nix
Per the firectl docs, read-only block devices must be suffixed with a `:ro` after the rootfs file path. Without this, we cannot attach a rootfs that's built inside the nix store. Attempting to run a VM that has its rootfs inside a NixOS /nix/store (that's mounted read-only) results is firecracker errors:
```
[root@host:~]# ./result/bin/microvm-run                                          
INFO[0000] Called startVMM(), setting up a VMM on control.socket                        
INFO[0000] VMM logging disabled.                                                                                                                                                
INFO[0000] VMM metrics disabled. …
```
=> Firecracker: root-drive must be suffixed with :ro

nixos-modules/microvm/system.nix
Nix store optimisation tries to create hardlinks between store paths
with identical contents. This fails when trying to create a hardlink
between different layers of the overlay.
Closes #50
=> Warn if trying to use nix store optimisation with writableStoreOverlay

nixos-modules/host.nix
When run multiple times, ln -sf ${runner} current tries to create
nested symlinks inside of the directory linked to by the previous
invokation.
Without -h, chown dereferences symlinks and tries to change the owner of
files in the nix store.
=> microvm-install fixes

nixos-modules/host.nix
I was trying out vfio pci passthrough, and got this error:
```
Nov 15 08:06:33 nas2 systemd[1]: Starting Setup MicroVM 'automation' devices for passthrough...
Nov 15 08:06:33 nas2 microvm-pci-devices@automation[41180]: /nix/store/hvza7mjgaqi3ybawya1mhzsv42f46mw7-unit-script-microvm-pci-devices_-start/bin/microvm-pci-devices_-start: line 5: modprobe: command not found
```
This PR solves it.
=> fix modprobe path

lib/runners/crosvm.nix
crosvm doesn't properly clean the control socket when it stops, ensure there is no control socket, to avoid "Address already in use" when it is trying to start again.
Signed-off-by: Mika Tammi <mika.tammi@unikie.com>
=> lib/runners/crosvm: Clean-up control socket

lib/runner.nix, lib/runners/cloud-hypervisor.nix, nixos-modules/host.nix, nixos-modules/microvm/options.nix
Changes regarding cloud-hypervisor (CHV):
- change the permission of the vfio dev  
- set memlock in limits
- add hugepage option 
@astro if you wish i could split this PR into separate ones.
=> CHV: fix vfio perm and limits + hugepages

README.md
The README.md states crosvm has no control socket, yet it appears to have one:
https://crosvm.dev/book/running_crosvm/advanced_usage.html?highlight=control%20sock#control-socket
and appears to be implemented here:
https://github.com/astro/microvm.nix/blob/main/lib/runners/crosvm.nix#L52
=> remove "no control socket" restriction in README

pkgs/microvm-command.nix
`microvm -r vmname` fails due to missing $NAME variable.
=> fix microvm -r command

lib/runners/cloud-hypervisor.nix, lib/runners/crosvm.nix, lib/runners/firecracker.nix, lib/runners/kvmtool.nix, lib/runners/qemu.nix
Created this to open discussion. Relates to #69 
On x86_64, some hypervisors are able to load the ELF-formatted vmlinux binaries, which have debugging symbols included. However, this does not apply currently for aarch64-linux.
Signed-off-by: Mika Tammi <mika.tammi@unikie.com>
=> Make QEMU, CrosVM, Cloud-Hypervisor, Firecracker and kvmtool work on both x86_64 and aarch64

lib/runners/qemu.nix
vfio-pci requires PCI bus for qemu
Otherwise you get errors like:
`qemu-system-x86_64: -device vfio-pci,host=0000:00:14.3,multifunction=on: No 'PCI' bus found for device 'vfio-pci'`
=> qemu: Require PCI for PCI passthrough on x86_64

lib/runner.nix, lib/runners/qemu.nix, nixos-modules/host.nix, nixos-modules/microvm/options.nix
Auto create macvtap interfaces with a service similar to tap interfaces. 
- Adds a `link` option to interfaces specifying which interface the auto-created macvtap should link to.
- Adds service that will create macvtap interfaces on the host
Example configuration:
```
microvm.interfaces = [{
type="macvtap";
id="macvtap1";  # name of the newly created interface on the host
link="eno2";  # name of an existing interfaces that the macvtap operates on
mac="00:00:00:00;00"; # the mac address of the macvtap interface
}];
```
Related to #80
=> Create macvtap interface link

nixos-modules/host.nix
Correctly pass `mode $mode` as arguments array instead of a string.
Ref #93 #80
=> fix(macvtap): correctly setup mode

nixos-modules/host.nix
Currently, accessing `config.microvm.vms.<name>.config` directly exposes the *content* of the configuration. This is undesirable because it hides (and prevent access to) any meta information returned by `eval-config.nix`. This is for example stuff like `options` which exposes the definition values and locations of options which is useful for debugging and necessary for some advanced stuff.
This change exposes the full generated attrset in the `config` attribute. This has no effect for users, the option is still used in the same way. (The old result can also still be accessed by adding `.config`).
=> fix: allow meta access to the generated declarative nixos systems

nixos-modules/microvm/mounts.nix
I started getting below error, looks like it's because `mounts.nix` was not created to be opted out:
```
error: The option `fileSystems."/nix/store".fsType' has conflicting definition values:
- In `/nix/store/5my0m9fdfsazzc5m6z0wc8b2k66xwnm3-source/modules': "zfs"
- In `/nix/store/3xmpkg4m13l8h2a278gqbwc8r0fz5f6w-source/nixos-modules/microvm/mounts.nix': "erofs"
Use `lib.mkForce value` or `lib.mkDefault value` to change the priority on any of these definitions.
```
=> make `nixos-modules/microvm/mounts.nix` opt-out

nixos-modules/host.nix
see https://gitlab.com/virtio-fs/virtiofsd/-/issues/104
=> Disable seccomp filter to fix crash on nixos-23.05

lib/runners/qemu.nix
The i8042 device is added to qemu command line for all platforms, whereas it's needed only for x86. It's already added for the platform in line #106.
=> Remove un-needed i8042 device from qemu command line

nixos-modules/microvm/mounts.nix
- This is a fix that closes https://github.com/astro/microvm.nix/issues/114
Since a fix upstream in nixpkgs seems to be non-trivial (the necessary modules are not in a direct dependency chain like with 9p), I would add these barriers to ensure that filesystem modules are always available.
=> fix: always wait for module loading for critical file systems and virtiofs

nixos-modules/host.nix
This is a necessary workaround for https://github.com/NixOS/nixpkgs/issues/219013
=> fix: explicitly empty the path of asDropin overrides to prevent clobbering it

lib/runners/qemu.nix
Fixes the `Property 'virtio-net-device.romfile' not found` error, if running `-M microvm` -kind of configuration on x86_64-linux.
=> Fix issue related to romfile= argument

nixos-modules/microvm/options.nix
=> nixos-modules/microvm/options: use nonEmptyStr instead of path for shares.*.source

pkgs/spectrum-os/cloud-hypervisor/0001-build-use-local-vhost.patch, pkgs/spectrum-os/cloud-hypervisor/0002-virtio-devices-add-a-GPU-device.patch, pkgs/spectrum-os/cloud-hypervisor/Cargo.lock, pkgs/spectrum-os/cloud-hypervisor/default.nix, pkgs/spectrum-os/cloud-hypervisor/vhost/0001-vhost_user-add-shared-memory-region-support.patch, pkgs/spectrum-os/cloud-hypervisor/vhost/0002-devices-vhost-user-add-protocol-flag-for-shmem.patch
Hello,
This PR:
* Updates the vendored version of cloud-hypervisor from upstream (identical in nixpkgs and spectrums nixpkgs atm)
* ~Removes rust-hypervisor-firmware because it's [currently broken](https://github.com/NixOS/nixpkgs/issues/256957) in nixpkgs and I don't think we need it, as cloud-hypervisor can boot kernel + initrds directly and we don't seem to depend on bootloaders?~
* ~Maybe controversal: rename cloud-hypervisor-graphics to just cloud-hypervisor and use the same build for graphical and non-graphical hosts alike. Happy to remove this or make it opt-in if needed, see commit msg for justification.~
=> Update cloud hypervisor

doc/src/faq.md
systemd-tmpfiles config has [7 columns](https://www.man7.org/linux/man-pages/man5/tmpfiles.d.5.html). This PR improves the faq example and avoid the following error:
`/etc/tmpfiles.d/00-nixos.conf:4: Invalid age '/var/lib/microvms/<vmname>/journal/<machineId>'.`
EDIT:
Thank you very much for your work on microvm.nix 🙏
=> Update faq.md systemd-tmpfiles

lib/runners/qemu.nix, nixos-modules/microvm/default.nix, nixos-modules/microvm/optimization.nix
This is based on my work on MapleCTF to run microvm.nix inside a docker
container (incidentally, an awesome microvm.nix use case) and have the
size not cause substantial issues.
Overall this saves about 700MB of closure size of a naive no-op VM
configuration at practically the sole cost of eating a qemu compile.
```
co/microvm.nix » nix path-info -sSh ./result1
/nix/store/ligbkxkl1hnz2pvj8d9dfic991zfc0s0-microvm-qemu-nixos     1.7K  756.3M
co/microvm.nix » nix path-info -sSh ./result-without
/nix/store/h218db586pc627ai96j5cq2gssbvaxk8-microvm-qemu-nixos     1.7K    1.4G
```
Without:
```
[root@nixos:~]# systemd-analyze time
Startup finished in 1.402s (kernel) + 8.830s (userspace) = 10.233s
multi-user.target reached after 8.830s in userspace.
```
With:
```
[root@nixos:~]# systemd-analyze …
```
=> nixos-modules: add closure size + startup time optimization

lib/runners/crosvm.nix
Note that "hidden = true" for the display doesn't work as intended for me, needed to patch crosvm to actually get rid of the display showing tty1. But that's true for cloud-hypervisor as well.
=> crosvm: sync gpu params with cloud-hypervisor

lib/runners/cloud-hypervisor.nix
The systemd unit ExecStop script for cloud-hypervisor used to wait for machine termination by detecting the closing of the cloud-hypervisor API socket. However, it seems that this socket is actually closed before the machine is safely shut down.
Therefore, this patch replaces the listen on the socket with a waitpid on the main PID, which is the cloud-hypervisor process. This process only terminates after the machine has properly shut down.
More information and experiment results are in #152
=> cloud-hypervisor: resolve issue #152 using waitpid

doc/src/SUMMARY.md, doc/src/advanced-network.md, doc/src/simple-network.md
This is much simpler than some odd private bridge/port-forwarding.
Fixes: #116.
=> simple-network.md: Adapt to place microVMs directly on LAN

nixos-modules/host.nix
As MicroVMs work fine without KSM enabled, it should probably be optional. While KSM can improve a lot of workloads, it can harm others, and so this configuration should not conflict with a value explicitly set by the user.
=> Make Kernel Samepage Merging optional

nixos-modules/host.nix
I wanted to mount a directory with space in the name, but that failed due to missing quotes in the `microvm-virtiofsd@` service.
```nix
microvm.shares = [{
tag = "tv_shows";
proto = "virtiofs";
source = "/tank/downloads/TV Shows";
mountPoint = "/home/ftp/TV Shows";
}];
```
With this change the mount works.
=> Fix spaces in virtiofs source

lib/runners/qemu.nix, nixos-modules/microvm/options.nix
Implements: https://github.com/astro/microvm.nix/issues/127
---
By setting a module of the form:
```
modules = [
{ nixpkgs.crossSystem.config = "aarch64-unknown-linux-gnu"; }
]
```
On the `lib.nixosSystem` call, and a specific CPU on the `nixosModules.microvm` call, such as:
```
microvm = {
cpu = "cortex-a53";
}
```
Allow a different CPU to be emulated by using qemu's Tiny Code Generator (TCG). While this will have a performance impact on the guest, it allows to experiment cross-system derivations on an emulated guest.
=> feat: allow to specify a CPU to emulate with a cross-system

nixos-modules/microvm/mounts.nix
This PR just removes unnecessary definitions of `neededForBoot = false`, which are currently set on all normal volumes added by users. Removing these makes it possible to set `neededForBoot = true` for some of them (e.g. when using impermanence) without requiring use of `lib.mkForce true` every time.
This removes unnecessary conflict messages and makes it clear that the `neededForBoot` property is _not_ set to `false` explicitly by microvm.nix, because in reality just the `neededForBoot = true` values are those that are serve a purpose.
=> fix: don't set `neededForBoot = false` if not necessary

lib/runners/qemu.nix
Use microvmConfig.cpu == null to check whether we should be doing virtualization with KVM or emulation of the CPU, instead of checking pkgs.buildPlatform == pkgs.hostPlatform. The latter kind of check causes microvm not start, if the system running microvms has been cross-compiled for example from x86_64-linux to aarch64-linux.
=> qemu: Fix cross-compilation

checks/default.nix, checks/startup-shutdown.nix, lib/default.nix, lib/runner.nix, nixos-modules/microvm/mounts.nix, nixos-modules/microvm/options.nix
This adds tests for the qemu-tcg backend that check that the emulated machine has the expected architecture. This check also works for the rest of hypervisors.
**However**, there is something fishy when running this test case. Please, check the first comment on this PR for the error.
If you have any idea how to tackle this issue I would be glad to update the PR. Thanks!
=> Add tests for qemu-tcg backend

nixos-modules/microvm/mounts.nix
See #186. Also adds a requires on module loading to 9p shares which can also be affected by module load order.
=> fix: wait for the correct mount before attempting to create an overlayfs (closes #186)

lib/runners/qemu.nix, nixos-modules/microvm/options.nix
For some applications like UART passthrough we want to disable the default qemu virtual serial (-serial chardev:stdio). With this flag in false we remove this virtual device and the ttyAMA0/S0 kernel console.
=> qemu: add option microvm.qemu.serialConsole

lib/runner.nix
Having multiple microvm's running on my server it's always hard to see in `top` which VM is taking up resources: all processes are named `cloud-hypervisor`. This patch renames the process `/nix/store/$hash-cloud-hypervisor` (or whatever hypervisor is used) to `microvm-$hostname` making it possible to distinguish the running VM's. I'm not sure if other people also find this desirable, if not, maybe this can be added behing a toggle flag?
PS. it only shows the microvm name in `top` if the full command line is shown (eg. pressing `c`).
=> Set microvm hostname as process name in runner

lib/runners/qemu.nix
From latest commit off main: c5074bb6d328a6071a70dcb097f8bcd208fce80a
Setting `vcpu > 1` for qemu guests would result in the following error during guest startup:
```
qemu-system-x86_64: -device virtio-net-device,netdev=host1, \
mac=02:00:00:00:00:01,mq=on,vectors=6: Property \
'virtio-net-device.vectors' not found
```
I believe this is because only `virtio-net-pci` supports `mq` and `vectors`. But its hard to tell
from the documentation that I found: https://www.linux-kvm.org/page/Multiqueue#Enable_MQ_feature
My hosts microvm configuration:
```
{
microvm.qemu = {
serialConsole = false;
extraArgs = [
"-serial" "pty"
];
};
microvm = {
vcpu = 2;
mem = 4096;
interfaces = [{
type = "tap";
id = "vm-host1";
mac = "02:00:00:00:00:01";
}];
volumes = [{ image = "/persist/microvm/host1.img"; …
```
=> qemu: dont set mq=on,vectors=N for virtio-net-device

doc/src/simple-network.md
I was troubleshooting this issue for a while, found the solution, and thought it'd be helpful to add to the docs. 
Essentially, the config laid out under "Simple Networking" breaks docker networking within the VMs, because it matches all `ether` interfaces, which includes the bridged `veth*` interfaces docker creates and uses for each container. Unmanaging these fixes the issue, as found in https://github.com/systemd/systemd/issues/28626.
=> Add docker/systemd-networkd doc snippet

lib/runners/qemu.nix
This is the bare-minimum fix to make sure the qemu runner doesn't crash on hosts with SGX available. I'm open for ideas on how to make this configurable if that's necessary.
Fixes: #212
Upstream issue: https://gitlab.com/qemu-project/qemu/-/issues/2142
=> qemu: fix crash when using sgx

lib/runner.nix
When running in aarch64 a x86 compiled version, the result microvm-run script uses x86 bash runtimeShell. Fixed by removing the buildPackages from runtimeShell.
=> runner: fixed cross-compilation

lib/runners/cloud-hypervisor.nix
If cloud-hypervisor crashes then the sockets don't get cleaned up and it won't be able to start
=> cloud-hypervisor: clean up notify sockets

lib/default.nix
See https://github.com/astro/microvm.nix/issues/229
=> Switch to truncate in createVolumesScript to avoid race conditions and support larger disk allocations

lib/runners/qemu.nix
Hello,
I've noticed that microvm.nix adds an EHCI controller for USB forwarding, while the documentation seems to recommend XHCI: https://www.qemu.org/docs/master/system/devices/usb.html#xhci-controller-support
Is there a reason for using EHCI? If so, I am happy to create an option instead.
=> Use xhci instead of ehci for USB

nixos-modules/microvm/store-disk.nix
We already do `gensquashfs --all-root` for `microvm.storeDiskType = "squashfs"`.
=> nixos-modules/microvm/store-disk: create squashfs with uid/gid 0

lib/default.nix, nixos-modules/microvm/options.nix
I have added a few variables to the btrfs filesystem creation to optimize it, for small filesystems and x64 CPUs, changes in order:
- -M for small filesystems
- --csum xxhash for fast x64 PCs.
=> Added support for btrfs filesystem.

lib/runners/cloud-hypervisor.nix
Similarly to qemu, cloud-hypervisor also emulates a serial device that gets mapped to ttyAMA0 on aarch64, adjust kernel command line accordingly.
=> cloud-hypervisor: Use correct console on aarch64

lib/runners/cloud-hypervisor.nix
We have kernelConsole value already defined but its not being used as argument. So removing hardcoded value and using kernelConsole value, which will fix issue console service crash issue on aarch64.
=> cloud-hypervisor: Remove hardcoded value of console

nixos-modules/host/default.nix
diff on one of the servers where I deployed this:
```
alsa-lib: 1.2.11 → ∅, -1640.9 KiB
alsa-topology-conf: 1.2.5.1 → ∅, -336.1 KiB
alsa-ucm-conf: 1.2.11 → ∅, -523.9 KiB
avahi: 0.8 → ∅, -1543.4 KiB
bluez: 5.75 → ∅, -9339.4 KiB
cairo: 1.18.0 → ∅, -1678.5 KiB
capstone: 5.0.1 → ∅, -9841.1 KiB
cdparanoia-III: 10.2 → ∅, -356.2 KiB
celt: 0.11.3 → ∅, -168.4 KiB
dconf: 0.40.0 → ∅, -308.5 KiB
dejavu-fonts-minimal: 2.37 → ∅, -742.6 KiB
dtc: 1.7.0 → ∅, -502.6 KiB
ell: 0.64 → ∅, -610.0 KiB
fdk-aac: 2.0.3 → ∅, -1479.6 KiB
ffmpeg-headless: 6.1.1 → ∅, -26156.4 KiB
fftw-single: 3.3.10 → ∅, -4119.5 KiB
flac: 1.4.3 → ∅, -703.8 KiB
fontconfig: 2.15.0 → ∅, -2065.4 KiB
fribidi: 1.0.13 → ∅, -154.3 KiB
gdk-pixbuf: 2.42.11 → 2.42.12
graphite2: 1.3.14 → ∅, -219.6 KiB
gst-plugins-base: 1.24.2 → ∅, -7361.0 KiB …
```
=> Use smaller qemu-utils for qemu-bridge-helper

lib/runner.nix
[fixes #263]
```
$ cat /var/lib/microvms/net-vm/current/bin/microvm-run
#!/nix/store/q449kdcw4lay790zri7gilgjzbgrq9fv-bash-aarch64-unknown-linux-gnu-5.2p26/bin/bash
```
```
$ file /nix/store/q449kdcw4lay790zri7gilgjzbgrq9fv-bash-aarch64-unknown-linux-gnu-5.2p26/bin/bash
/nix/store/q449kdcw4lay790zri7gilgjzbgrq9fv-bash-aarch64-unknown-linux-gnu-5.2p26/bin/bash: ELF 64-bit LSB executable, ARM aarch64, version 1 (SYSV), dynamically linked, interpreter /nix/store/585wgmdaa952yyla33kffm733a8xbh32-glibc-aarch64-unknown-linux-gnu-2.39-52/lib/ld-linux-aarch64.so.1, BuildID[sha1]=87efdae73b275a3eb14444a2d0ff21771c486c3a, for GNU/Linux 3.10.0, not stripped
```
```
$ uname -a
Linux ghaf-host 5.10.120 #1-NixOS SMP Tue Jan 1 00:00:00 UTC 1980 aarch64 GNU/Linux
```
=> Fix cross-compilation issue with runners

nixos-modules/host/default.nix
The quotes around `$SOURCE` need to be escaped, currently it breaks virtiofs sources which contain a space in the path.
=> Fix quoting of virtiofs sources in supervisord config

lib/runners/alioth.nix, lib/runners/cloud-hypervisor.nix, lib/runners/crosvm.nix, lib/runners/firecracker.nix, lib/runners/kvmtool.nix, lib/runners/qemu.nix, lib/runners/stratovirt.nix, nixos-modules/microvm/options.nix
I only added support for cloud-hypervisor. The options are also supported in qemu (and possibly others) but i am just using cloud hypervisor.
serial is not documented yet, but it's been supported by cloud hypervisor for a year.
One thing to watch out for is the length of serial, it has to be 20 characters (or less, maybe).
Direct does not improve I/O performance per se, it mostly reduces overhead and makes VMs less noisy (O_DIRECT).
Maybe this PR should be closed wihout merging and we should have a manual way (i.e. a blanket "extraOpts" option) to specify hypervisor specific options because the doesn't pattern doesnt seem sustainable.
I am not using linux and I didn't want to spend time on setting up the formatter for nix (I am usually using nixfmt in my flake). So if you would like to …
=> Add direct and serial options to disk devices

nixos-modules/host/options.nix, nixos-modules/microvm/options.nix
=> doc: fix literalExpression in examples

lib/runners/cloud-hypervisor.nix
Since https://github.com/systemd/systemd/commit/13b67b61b3b4a5356f5d1b29b51137b8e336aa55
systemd shutdown the write end of one end of the VSOCK.
cloud-hypervisor virtio-sock code does not handle well partial shutdown of the
stream.
socat `-T` flag can serve as a workaround to mask this bug.
> Total inactivity timeout: when socat is already in the transfer loop and
> nothing has happened for <timeout> [timeval] seconds (no data arrived, no
> interrupt occurred...) then it terminates. Useful with protocols like UDP that
> cannot transfer EOF.
Co-authored-by: Puck Meerburg <puck@puckipedia.com>
Signed-off-by: Raito Bezarius <masterancpp@gmail.com>
All thanks to Puck for the debugging of this.
=> fix(cloud-hypervisor/vsock): apply a workaround for notify sockets

CHANGELOG.md, lib/runner.nix, nixos-modules/host/default.nix, nixos-modules/host/options.nix, nixos-modules/microvm/default.nix, nixos-modules/microvm/interfaces.nix, nixos-modules/microvm/options.nix, nixos-modules/microvm/pci-devices.nix, nixos-modules/microvm/virtiofsd/default.nix, nixos-modules/microvm/virtiofsd/supervisord-event-handler.py
@SuperSandro2000 Can you review pls? Note the simplified `virtiofsdCount` logic.
=> nixos-modules: move virtiofsd from host to microvm

lib/runner.nix, nixos-modules/microvm/interfaces.nix
#291 introduced two bugs related to macvtaps:
- multiple definition of `tapMultiQueue` in the passthru attributes.
I'm guessing the on I removed shouldn't be there as it's just the other one without
the default case.
- wrong type of `binScripts.macvtap-down`
=> fix macvtaps

nixos-modules/microvm/interfaces.nix
Found runtime bug for macvtaps. They explicitely need the keyword `mode`.
=> fix: macvtap mode syntax

nixos-modules/microvm/interfaces.nix
When the host has IPv6 disabled via "ipv6.disable=1" completely the service to setup up a macvtap interface fails because it tries to write to the nonexistant "/proc/sys/net/ipv6" directory. Fix this by checking for its presence first.
=> fix: only disable IPv6 when present

lib/runners/qemu.nix
Copied from existing cloud-hypervisor implementation. Tested by launching a MicroVM on a system that expects MicroVMs to use notify sockets, and additionally using plain socat in a second terminal.
=> qemu: support notify sockets

nixos-modules/microvm/options.nix
It was slightly overlooked in last refactor.
=> fix(options): undefined variable 'kernelAtLeast'

lib/runners/cloud-hypervisor.nix
When BalloonMemory was not 0 evaluation of derivations failed after PR #324 made deflate-on-oom optional.
The new optional set containing the argument was only merged with the other arguments, after those were converted into a list leading to a type mismatch.
fixes: #326
=> fix: evaluation wont fail when BalloonMemory is enabled

lib/runners/qemu.nix, nixos-modules/microvm/options.nix
This option could be useful in case we may need to pass any extra arguments to pci device.
For example:
`-device vfio-pci,host=x,multifunction=on,id=hostId,x-igd-opregion=on`
=> qemu: add deviceExtraArgs option for devices

lib/runners/cloud-hypervisor.nix
bcabdfff46d3bb7806e6e358982ad457ee650fb7 (#325) indroduced additional device arguments, which were not handled by the cloud-hypervisor implementation
=> cloud-hypervisor: fix pci device config

doc/src/conventions.md, lib/runner.nix, lib/runners/alioth.nix, lib/runners/cloud-hypervisor.nix, lib/runners/crosvm.nix, lib/runners/firecracker.nix, lib/runners/kvmtool.nix, lib/runners/qemu.nix, lib/runners/stratovirt.nix, nixos-modules/microvm/interfaces.nix, nixos-modules/microvm/options.nix, nixos-modules/microvm/store-disk.nix
Closes #228
I kinda went and removed dead code on every file I opened while debugging.
=> Allow to discard all toplevel references when using erofs

nixos-modules/host/default.nix
A previous PR #231 ("Increased microvm default timeout stop to 2m30s") changed the default TimeoutStopSec= to 150 to avoid the VMs almost finish booting, but TimeoutStopSec=[1] is the amount of time systemd waits for the service to stop, not start. Switch to TimeoutSec= to set both TimeoutStartSec= and TimeoutStopSec=.
[1] https://www.freedesktop.org/software/systemd/man/latest/systemd.service.html#TimeoutStopSec=
=> Change TimeoutStopSec= to TimeoutSec=

nixos-modules/microvm/virtiofsd/default.nix
substituteAll has been deprecated so will start to cause warnings on 25.05 and nixos-unstable.
https://github.com/NixOS/nixpkgs/pull/395275
=> fix(substituteAll): use replaceVars

lib/runners/cloud-hypervisor.nix, lib/runners/crosvm.nix, lib/runners/qemu.nix
This is an experimental attempt to implement #350 -- a dynamic PCI device id for passthrought.
Actual change move forming part of qemu command line outside of common shell escaping, replace it with simple concatenation. This allow use something like  `vfio-pci,host=$(/path/to/detect-id.sh)`.
Weak sides:
* Currently only qemu implemented
* Very barely tested
* possible security implications (why it _was_ under escaping)
* formatting probably wrong (`nix fmt` didn't work, what you use for format)
This is (not yet) a final solution, but PoC and point for a discussion
=> Moving pci/usb ids out of shell escaping

lib/default.nix, lib/runner.nix
Use pkgs instead of pkgs.buildPackages to ensure e2fsprogs and other utilities are built for the target ARM64 architecture rather than the build x86 architecture. This resolves the "Exec format error" when running chattr and mkfs.ext4.
=> fix: use target architecture binaries for disk volume creation

flake.lock, flake.nix
I was unable to run `cloud-hypervisor` with `graphics` enabled on `main`.
This PR:
- fixes spectrum-os `cloud-hypervisor` import
- updates spectrum-os flake to the latest version
=> fix: spectrum-os overlay

lib/runners/crosvm.nix
This fixes a syntax error when building a crosvm vm with pci passthrough enabled:
```
… while calling 'concatMapStringsSep'
at /nix/store/xnr2xjs0clkhlhqfc3vqcmhnnwdk3c5p-source/lib/strings.nix:231:13:
230|   concatMapStringsSep =
231|     sep: f: list
|             ^
232|     concatStringsSep sep (map f list);
error: cannot coerce a list to a string
```
=> Fix build error when using crosvm with pci passthrough

nixos-modules/host/default.nix, nixos-modules/host/options.nix
should resolve issue #317 
Make the default timeout for vm starup an option
=> Add option to configure TimeoutSec for vms

lib/default.nix, lib/runner.nix, lib/runners/cloud-hypervisor.nix, nixos-modules/microvm/asserts.nix, nixos-modules/microvm/options.nix
The cloud-hypervisor command line interface unfortunately doesn't support
multiple instances of the same arg with a different value, so we have to resort
to these extra module options rather than using extraArgs.
To make matters even worse, the `--platform` argument (of which there can be
only one), is overloaded with different types of sub-args that also need to be
provided multiple times.
This commit allows the operator to add oem strings (for example to pass systemd
credentials), as well as raw platform options as needed.
=> cloud-hypervisor: add platformOEMStrings and `--platform` merging

lib/runners/cloud-hypervisor.nix
This seems to have been dropped by mistake: https://github.com/microvm-nix/microvm.nix/pull/379/files#diff-e9029b60b67bf9e6960f7b3b27dc3d266a56c8d089250acce3bfe1ccec94fc25L145
Without this change, you can set a CID for the VM's vsock, but the generated systemd service will still have `Type=simple` and won't wait for the notification.
=> cloud-hypervisor: properly advertise support for systemd-notify

lib/runners/qemu.nix
Hi!
While I was testing some things I encountered an issue with the `credentialFiles` option. It worked fine with 0 or 1 credential, but when I provided 2 credentials, the VM no longer recognized them.
This commit should fix the issue, I tested it with both my configuration (2 credentials) and the `#qemu-example` configuration.
=> Fix credentialFiles option in QEMU not working when more than one credential is provided

nixos-modules/microvm/options.nix
I think there is no further explanation needed :-)
=> docs: Add "(in MiB)" to `volumes.*.size`

lib/runners/qemu.nix
Reintroduce conditional logic to select `qemu_kvm` for Linux hosts, while defaulting to `qemu` for other platforms.
Logic was removed https://github.com/microvm-nix/microvm.nix/commit/c034812a41da001e92e587965204cb0da698da72#diff-e281468e7547e8499c2ec97ce9d1b6c09fee9c518d20378bc7d7facc56d7e9b2L41-L50 
This will enable Linux Hosts to utilize `qemu_kvm` with additional advantages.
=> Qemu: Select qemu_kvm on Linux hosts

nixos-modules/microvm/options.nix, nixos-modules/microvm/store-disk.nix
- Introduce `microvm.registerClosure` option.
- Gate `regInfo` kernel cmdline and `load-db` behind `registerClosure`.
This way, writableStoreOverlay may be (ab)used with a persistent Nix DB:
- If guest Nix encounters a store path present in the lowerdir, it'll have to realize it, i.e. write a copy to the upper dir. There's a chance we'll actually get a different copy (e.g. due to a different substitutor and/or non-deterministic builds), possibly leading to inconsistency.
- Perhaps inconsistencies can be avoided by registering the ro-store as a "substitutor"?
- We can now swap the guest image, GC the Host's store, and reboot. This is tolerable, because system paths were never registered in the guest db, unless re-"realized" and copied to the upperdir.
This is not a pretty solution. E.g. …
=> feat(writableStoreOverlay): make loading regInfo optional
